### ISSUE TITLE
Cannot load less or css files in production

### ISSUE THREAD

**Issue by phillipskevin** [donejs/autorender#42]
I'm not positive that this is an autorender issue, but after generating an app with `donejs@alpha` and starting the app in production mode, I get this error:

```
done-serve starting on http://localhost:8080
Potentially unhandled rejection [6] TypeError: Error loading "alpha-test@0.0.0#styles.less!steal-less@1.1.0#less" at file:C:/Users/kphil/dev/alpha-test/src/styles.less
Error loading "alpha-test@0.0.0#styles.less!steal-less@1.1.0#less" from "alpha-test@0.0.0#index.stache!done-autorender@1.0.0-alpha.2#src/autorender" at file:C:/Users/kphil/dev/alpha-test/src/index.stache
Cannot read property 'forwardSlashMap' of undefined
    at Object.name (file:C:/Users/kphil/dev/alpha-test/dist/bundles/alpha-test/index.js:6:4751)
    at Loader.n (file:C:/Users/kphil/dev/alpha-test/dist/bundles/alpha-test/index.js:6:384)
    at r (file:C:/Users/kphil/dev/alpha-test/dist/bundles/alpha-test/index.js:6:3913)
    at file:C:/Users/kphil/dev/alpha-test/dist/bundles/alpha-test/index.js:6:3994
    at tryCatchReject (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:1183:30)
    at runContinuation1 (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:1142:4)
    at Rejected.when (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:963:4)
    at Pending.run (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:821:13)
    at Scheduler._drain (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:97:19)
    at Scheduler.drain (C:\Users\kphil\dev\alpha-test\node_modules\steal-es6-module-loader\dist\es6-module-loader.src.js:62:9)
```

This is what the bundles config looks like in index.js:
```
System.bundles = {"bundles/alpha-test/index.css!":["alpha-test@1.0.0#styles.less!steal-less@1.1.0#less"]};
```

Loading the production.html file works just fine.

**Comment by phillipskevin** [comment]
Issue moved to [donejs/done-ssr #206](https://github.com/donejs/done-ssr/issues/206) via [**ZenHub**](https://www.zenhub.com/)
